import type { Metadata } from "next";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import ConfigProvider from "antd/es/config-provider";
import { kanit } from "@/app/font";
import LayoutManager from "../_component/layoutManager";
import AppWrapper from "../_context/wrapper";

export const metadata: Metadata = {
  title: "Administrator | KMS",
  description: "Generated by test",
};

export default function PageLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ConfigProvider
      theme={{
        token: {
          fontFamily: kanit.style.fontFamily,
        },
      }}
    >
      <section className={kanit.variable}>
        <AntdRegistry>
          <AppWrapper>
            <LayoutManager>{children}</LayoutManager>
          </AppWrapper>
        </AntdRegistry>
      </section>
    </ConfigProvider>
  );
}
