import type { Metadata } from "next";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { kanit } from "../font";
import ConfigProvider from "antd/es/config-provider";

export const metadata: Metadata = {
  title: "Administrator | KMS",
  description: "Generated by test",
};

export default function PageLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ConfigProvider
      theme={{
        token: {
          fontFamily: kanit.style.fontFamily,
        },
      }}
    >
      <section className={kanit.variable}>
        <AntdRegistry>{children}</AntdRegistry>
      </section>
    </ConfigProvider>
  );
}
