import type { Metadata } from "next";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { kanit } from "./font";
import { GoogleTagManager } from "@next/third-parties/google";



// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={kanit.variable}>
       <GoogleTagManager gtmId="GTM-TM7H4FZ" />
      <body >
        <AntdRegistry >{children}</AntdRegistry>
      </body>
    </html>
  );
}
