import type { Metadata } from "next";
import Header from "./_component/header";
import Footer from "./_component/footer";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { kanit } from '../font'

export const metadata: Metadata = {
  title: "| KMS",
  // description: "Generated by test",
};

export default function PageLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section className={kanit.variable}>
      <Header />
      <AntdRegistry>{children}</AntdRegistry>
      <Footer />
    </section>
  );
}
